server.port=18081

# OpenAI
# chat-model
langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com
langchain4j.open-ai.chat-model.api-key=${deepseek.api.key}
langchain4j.open-ai.chat-model.model-name=deepseek-v4-pro
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
# streaming-chat-model
langchain4j.open-ai.streaming-chat-model.base-url=https://api.deepseek.com
langchain4j.open-ai.streaming-chat-model.api-key=${deepseek.api.key}
langchain4j.open-ai.streaming-chat-model.model-name=deepseek-v4-pro
langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true

# Ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen3.5:0.8b

# \u663E\u793A\u914D\u7F6E\u5927\u6A21\u578BGPT
# GPT
langchain4j.custom.chat-models.gpt.base-url=https://api.dwai.cloud/v1
langchain4j.custom.chat-models.gpt.api-key=${gpt.api.key}
langchain4j.custom.chat-models.gpt.model-name=gpt-5.5
langchain4j.custom.chat-models.gpt.log-requests=true
langchain4j.custom.chat-models.gpt.log-responses=true

langchain4j.custom.streaming-chat-model.gpt.base-url=https://api.dwai.cloud/v1
langchain4j.custom.streaming-chat-model.gpt.api-key=${gpt.api.key}
langchain4j.custom.streaming-chat-model.gpt.model-name=gpt-5.5
langchain4j.custom.streaming-chat-model.gpt.log-requests=true
langchain4j.custom.streaming-chat-model.gpt.log-responses=true
