server.port=18080

# ???????
# OpenAI
# chat-model
langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com
langchain4j.open-ai.chat-model.api-key=${deepseek.api.key}
langchain4j.open-ai.chat-model.model-name=deepseek-v4-pro
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
# streaming-chat-model
langchain4j.open-ai.streaming-chat-model.base-url=https://api.deepseek.com
langchain4j.open-ai.streaming-chat-model.api-key=${deepseek.api.key}
langchain4j.open-ai.streaming-chat-model.model-name=deepseek-v4-pro
langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true

# Ollama
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=qwen3.5:0.8b

# ???????
# GPT
langchain4j.custom.chat-models.gpt.base-url=https://api.dwai.cloud/v1
langchain4j.custom.chat-models.gpt.api-key=sk-688d75e761ba6ce30aa048baced5941d7d3f3f9aee77490e1109bdd6ae03032c
langchain4j.custom.chat-models.gpt.model-name=gpt-5.5
langchain4j.custom.chat-models.gpt.log-requests=true
langchain4j.custom.chat-models.gpt.log-responses=true

langchain4j.custom.streaming-chat-model.gpt.base-url=https://api.dwai.cloud/v1
langchain4j.custom.streaming-chat-model.gpt.api-key=sk-688d75e761ba6ce30aa048baced5941d7d3f3f9aee77490e1109bdd6ae03032c
langchain4j.custom.streaming-chat-model.gpt.model-name=gpt-5.5
langchain4j.custom.streaming-chat-model.gpt.log-requests=true
langchain4j.custom.streaming-chat-model.gpt.log-responses=true
