server.port=18080

# 1. \u5F00\u542F H2 \u63A7\u5236\u53F0\u529F\u80FD
spring.h2.console.enabled=true
# 2. \u8BBE\u7F6E\u63A7\u5236\u53F0\u7684\u8BBF\u95EE\u8DEF\u5F84\uFF08\u9ED8\u8BA4\u662F /h2-console\uFF0C\u4F60\u4E5F\u53EF\u4EE5\u81EA\u5B9A\u4E49\uFF09\uFF0C\u6253\u5F00\u6D4F\u89C8\u5668\u8BBF\u95EE\uFF1Ahttp://localhost:\u7AEF\u53E3\u53F7/h2-console
spring.h2.console.path=/h2-console
# 3. \u5141\u8BB8\u5728\u7F51\u9875\u4E0A\u67E5\u770B\u548C\u4FEE\u6539\u6570\u636E\u5E93\uFF08\u5F00\u53D1\u73AF\u5883\u5EFA\u8BAE\u5F00\u542F\uFF09
spring.h2.console.settings.web-allow-others=true

# OpenAI
# chat-model
# dev.langchain4j.openai.spring.ChatModelProperties
langchain4j.open-ai.chat-model.base-url=https://api.deepseek.com
langchain4j.open-ai.chat-model.api-key=${deepseek.api.key}
langchain4j.open-ai.chat-model.model-name=deepseek-v4-pro
langchain4j.open-ai.chat-model.log-requests=true
langchain4j.open-ai.chat-model.log-responses=true
# streaming-chat-model
langchain4j.open-ai.streaming-chat-model.base-url=https://api.deepseek.com
langchain4j.open-ai.streaming-chat-model.api-key=${deepseek.api.key}
langchain4j.open-ai.streaming-chat-model.model-name=deepseek-v4-pro
langchain4j.open-ai.streaming-chat-model.log-requests=true
langchain4j.open-ai.streaming-chat-model.log-responses=true

# Ollama
# dev.langchain4j.ollama.spring.ChatModelProperties
langchain4j.ollama.chat-model.base-url=http://localhost:11434
langchain4j.ollama.chat-model.model-name=chatgpt1/qwythos-9b-claude-mythos-5-1m-abliterated:latest
langchain4j.ollama.chat-model.log-requests=true
langchain4j.ollama.chat-model.log-responses=true
# PT30S = 30 \u79D2\uFF0CPT2M  = 2 \u5206\u949F\uFF0CPT1H  = 1 \u5C0F\u65F6\u3002
# \u5728 Spring Boot \u914D\u7F6E\u91CC\uFF0C\u4E00\u822C\u66F4\u63A8\u8350\u5199\u5F97\u76F4\u89C2\u4E00\u70B9\uFF0C\u5982\uFF1A300s
langchain4j.ollama.chat-model.timeout=120s
#langchain4j.ollama.chat-model.timeout=PT2M


# \u663E\u793A\u914D\u7F6E\u5927\u6A21\u578BGPT
# GPT
langchain4j.custom.chat-models.gpt.base-url=https://api.dwai.cloud/v1
langchain4j.custom.chat-models.gpt.api-key=${gpt.api.key}
langchain4j.custom.chat-models.gpt.model-name=gpt-5.5
langchain4j.custom.chat-models.gpt.log-requests=true
langchain4j.custom.chat-models.gpt.log-responses=true
langchain4j.custom.streaming-chat-model.gpt.base-url=https://api.dwai.cloud/v1
langchain4j.custom.streaming-chat-model.gpt.api-key=${gpt.api.key}
langchain4j.custom.streaming-chat-model.gpt.model-name=gpt-5.5
langchain4j.custom.streaming-chat-model.gpt.log-requests=true
langchain4j.custom.streaming-chat-model.gpt.log-responses=true
# Deepseek
langchain4j.custom.chat-models.deepseek.base-url=https://api.deepseek.com
langchain4j.custom.chat-models.deepseek.api-key=${deepseek.api.key}
langchain4j.custom.chat-models.deepseek.model-name=deepseek-v4-pro
langchain4j.custom.chat-models.deepseek.log-requests=true
langchain4j.custom.chat-models.deepseek.log-responses=true
langchain4j.custom.streaming-chat-model.deepseek.base-url=https://api.deepseek.com
langchain4j.custom.streaming-chat-model.deepseek.api-key=${deepseek.api.key}
langchain4j.custom.streaming-chat-model.deepseek.model-name=deepseek-v4-pro
langchain4j.custom.streaming-chat-model.deepseek.log-requests=true
langchain4j.custom.streaming-chat-model.deepseek.log-responses=true
